// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from './types';

const SUPABASE_URL = "https://ywtiawyxktzpennyvzpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_mI4JF_WxrC0RjOBLz8slvA_m8sh8Mub";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_ANON_KEY
);